sudo: required
services:
  - docker

before_install:
  # decrypt GCloud service account
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in gcloud-service-account.json.enc -out gcloud-service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file gcloud-service-account.json
  - gcloud config set project multi-k8s-259717
  - gcloud config set compute/zone europe-west1-c
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t thegli/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true thegli/react-test npm run test

