sudo: required

services:
  - docker

env:
  global:
    # used as uuid for image tagging
    - GIT_SHA=$(git rev-parse HEAD)
    # suppress prompts in gcloud commands
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
  # decrypt GCloud service account
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in gcloud-service-account.json.enc -out gcloud-service-account.json -d
  # install GCloud SDK
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  # configure k8s environment
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file gcloud-service-account.json
  - gcloud config set project multi-k8s-259717
  - gcloud config set compute/zone europe-west1-c
  - gcloud container clusters get-credentials multi-cluster
  # log in to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # build client using test settings
  - docker build -t thegli/react-test -f ./client/Dockerfile.dev ./client

script:
  # execute tests on client
  - docker run -e CI=true thegli/react-test npm run test

deploy:
  provider: script
  # builds and pushes the Docker images (we are stilled logged in Docker CLI)
  script: bash ./deploy.sh
  on:
    branch: master