apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim
spec:
  # used by a single node only
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi